# Generated by Django 3.2 on 2022-12-05 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20221205_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(null=True, upload_to='customers/cars/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=40, null=True, verbose_name='Name'),
        ),
    ]
