# Generated by Django 3.2 on 2022-12-08 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_auto_20221206_0644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Customer`s Car', 'verbose_name_plural': 'Customers` Cars'},
        ),
    ]
