# Generated by Django 3.2 on 2022-12-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_alter_car_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(null=True, upload_to='brands/', verbose_name='Logo'),
        ),
    ]
