# Generated by Django 3.2 on 2023-01-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_auto_20230126_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='name_ar',
            field=models.CharField(max_length=40, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_en',
            field=models.CharField(max_length=40, null=True, verbose_name='Name'),
        ),
    ]
