# Generated by Django 3.2 on 2022-12-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221204_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
