# Generated by Django 3.2 on 2023-01-26 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20221205_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='customers/images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('CUSTOMER', 'Customer')], max_length=50, verbose_name='Role'),
        ),
    ]
