# Generated by Django 3.2 on 2023-02-02 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20230126_2308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'verbose_name': 'Customer Profile', 'verbose_name_plural': 'Customer Profiles'},
        ),
    ]
