# Generated by Django 3.2 on 2022-12-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(blank=True, help_text='Leaving this field empty will generate a random code.', max_length=100, null=True, unique=True, verbose_name='Code'),
        ),
    ]
