# Generated by Django 3.2 on 2022-12-28 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_auto_20221228_2002'),
        ('booking', '0002_alter_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='car.car', verbose_name='Car'),
        ),
        migrations.AddField(
            model_name='booking',
            name='earned_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Earned Amount'),
        ),
        migrations.AddField(
            model_name='booking',
            name='expense_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Expense Amount'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='note',
            field=models.TextField(blank=True, help_text='Tell us more about car issues and parts that need to be maintained ...etc. ', max_length=400, null=True, verbose_name='Note'),
        ),
    ]
