# Generated by Django 3.2 on 2022-12-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_schedule_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='schedule_at',
            field=models.DateTimeField(help_text='When would you like to book?', verbose_name='Schedule At'),
        ),
    ]
