# Generated by Django 3.2 on 2023-01-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_booking_schedule_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(help_text='What is this expense for?', max_length=500, verbose_name='Cause')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Amount')),
                ('paid_at', models.DateTimeField(help_text='When this expense is paid?', verbose_name='Paid At')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
            ],
        ),
    ]
