# Generated by Django 3.2 on 2023-01-27 20:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230126_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_ar',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='post',
            name='body_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
    ]
