# Generated by Django 3.2 on 2022-12-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20221205_0215'),
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='brand',
            field=models.ManyToManyField(to='car.Brand'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='services',
            field=models.ManyToManyField(to='workshop.Service'),
        ),
    ]
