# Generated by Django 3.2 on 2022-12-05 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_auto_20221205_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportissue',
            name='date_of_issue',
            field=models.DateTimeField(null=True, verbose_name='When the issue occurred?'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='workshop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='workshop.workshop'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='workshop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rates', to='workshop.workshop'),
        ),
    ]
