# Generated by Django 3.2 on 2022-12-05 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_auto_20221205_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportissue',
            name='attachment',
            field=models.FileField(blank=True, help_text='Upload any kind of attachment that could help to clarify more about the issue', null=True, upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='reportissue',
            name='workshop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='workshop.workshop'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('1', 'Related To Brand'), ('0', 'Not Related To Brand')], max_length=50, verbose_name='Service Type'),
        ),
    ]
