# Generated by Django 3.2 on 2022-12-05 18:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_auto_20221205_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activate'),
        ),
    ]
