# Generated by Django 3.2 on 2022-12-13 11:08

from django.db import migrations, models
import django.db.models.deletion
import workshop.models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0006_auto_20221205_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='map_link',
        ),
        migrations.AddField(
            model_name='workshop',
            name='close_at',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='open_at',
            field=models.TimeField(null=True),
        ),
        migrations.CreateModel(
            name='WorkShopVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('link', models.URLField()),
                ('workshop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='workshop.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='WorkShopLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(blank=True, null=True, validators=[workshop.models.validate_map_link])),
                ('address', models.CharField(max_length=400)),
                ('workshop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='workshop.workshop')),
            ],
        ),
    ]
