# Generated by Django 3.2 on 2022-12-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0007_auto_20221213_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='model_year_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='model_year_start',
            field=models.DateField(null=True),
        ),
    ]
