# Generated by Django 3.2 on 2022-12-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0008_auto_20221225_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
