# Generated by Django 3.2 on 2023-01-26 21:08

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import workshop.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20230126_2308'),
        ('car', '0009_auto_20230126_2308'),
        ('workshop', '0011_alter_rate_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='rate',
            options={'verbose_name': 'Rating', 'verbose_name_plural': 'Ratings'},
        ),
        migrations.AlterModelOptions(
            name='reportissue',
            options={'verbose_name': 'Report Issue', 'verbose_name_plural': 'Report Issues'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='workshop',
            options={'verbose_name': 'WorkShop', 'verbose_name_plural': 'WorkShops'},
        ),
        migrations.AlterModelOptions(
            name='workshoplocation',
            options={'verbose_name': 'WorkShop Location', 'verbose_name_plural': 'WorkShop Locations'},
        ),
        migrations.AlterModelOptions(
            name='workshopvideo',
            options={'verbose_name': 'Work Shop Video', 'verbose_name_plural': 'Work Shop Videos'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='accounts.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='workshop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='workshop.workshop', verbose_name='Workshop'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rates', to='accounts.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='value',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='workshop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rates', to='workshop.workshop', verbose_name='Workshop'),
        ),
        migrations.AlterField(
            model_name='reportissue',
            name='attachment',
            field=models.FileField(blank=True, help_text='Upload any kind of attachment that could help to clarify more about the issue', null=True, upload_to='reports/', verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='reportissue',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='reportissue',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='accounts.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='reportissue',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='reportissue',
            name='suggestion',
            field=models.TextField(blank=True, null=True, verbose_name='Suggestion'),
        ),
        migrations.AlterField(
            model_name='reportissue',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='reportissue',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='reportissue',
            name='workshop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='workshop.workshop', verbose_name='Workshop'),
        ),
        migrations.AlterField(
            model_name='service',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='brands',
            field=models.ManyToManyField(to='car.Brand', verbose_name='Brands'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='close_at',
            field=models.TimeField(null=True, verbose_name='Close At'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='description',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='workshops/images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='model_year_end',
            field=models.DateField(null=True, verbose_name='Model Year End'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='model_year_start',
            field=models.DateField(null=True, verbose_name='Model Year Start'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='open_at',
            field=models.TimeField(null=True, verbose_name='Open At'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='services',
            field=models.ManyToManyField(to='workshop.Service', verbose_name='Services'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='workshoplocation',
            name='address',
            field=models.CharField(max_length=400, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='workshoplocation',
            name='link',
            field=models.TextField(blank=True, null=True, validators=[workshop.models.validate_map_link], verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='workshoplocation',
            name='workshop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='workshop.workshop', verbose_name='Workshop'),
        ),
        migrations.AlterField(
            model_name='workshopvideo',
            name='link',
            field=models.URLField(verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='workshopvideo',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='workshopvideo',
            name='workshop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='workshop.workshop', verbose_name='Workshop'),
        ),
    ]
