# Generated by Django 3.2 on 2022-12-08 08:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20221208_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='phone_number',
            field=models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{11}$', 'Invalid Phone Number')]),
        ),
    ]
