# Generated by Django 3.2 on 2022-12-08 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_contactus_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us'},
        ),
    ]
