# Generated by Django 3.2 on 2022-12-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_alter_contactus_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='maininfo',
            name='close_at',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='open_at',
            field=models.TimeField(null=True),
        ),
    ]
