# Generated by Django 3.2 on 2022-12-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20221213_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='maininfo',
            name='why_us',
            field=models.TextField(null=True, verbose_name='Why do you choose us?'),
        ),
    ]
