# Generated by Django 3.2 on 2022-12-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_headerimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerimage',
            name='active',
            field=models.BooleanField(default=True, help_text='Setting it to false, makes the image disappear from homepage'),
        ),
        migrations.AlterField(
            model_name='headerimage',
            name='alt',
            field=models.CharField(help_text='Text is meant to convey the “why” of the image as it relates to the content of a document or webpage', max_length=250, verbose_name='Alternative (Alt) '),
        ),
    ]
