# Generated by Django 3.2 on 2023-01-26 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_auto_20221230_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='first_name',
            field=models.CharField(max_length=120, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='last_name',
            field=models.CharField(max_length=120, null=True, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone_number',
            field=models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{11}$', 'Invalid Phone Number')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(max_length=250, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='cookiepolicy',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='cookiepolicy',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='faqs',
            name='answer',
            field=models.TextField(verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='faqs',
            name='quote',
            field=models.CharField(max_length=1000, verbose_name='Quote'),
        ),
        migrations.AlterField(
            model_name='headerimage',
            name='active',
            field=models.BooleanField(default=True, help_text='Setting it to false, makes the image disappear from homepage', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='headerimage',
            name='alt',
            field=models.CharField(help_text='Text is meant to convey the “why” of the image as it relates to the content of a document or webpage', max_length=250, verbose_name='Alternative (Alt)'),
        ),
        migrations.AlterField(
            model_name='headerimage',
            name='image',
            field=models.ImageField(upload_to='home/header', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='close_at',
            field=models.TimeField(null=True, verbose_name='Close At'),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='facebook',
            field=models.URLField(verbose_name='Facebook Link'),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='instagram',
            field=models.URLField(verbose_name='Instagram Link'),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='mail',
            field=models.EmailField(max_length=254, verbose_name='Web Email'),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='open_at',
            field=models.TimeField(null=True, verbose_name='Open At'),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='Telegram Link'),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='twitter',
            field=models.URLField(verbose_name='Twitter Link'),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='whatsapp',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]{11}$', 'Invalid Phone Number')], verbose_name='Whatsapp Number'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='termsofservice',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='termsofservice',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='works',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='works',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Title'),
        ),
    ]
