# Generated by Django 3.2 on 2023-01-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_auto_20230126_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='description_ar',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_ar',
            field=models.CharField(max_length=500, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='cookiepolicy',
            name='description_ar',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='cookiepolicy',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='cookiepolicy',
            name='title_ar',
            field=models.CharField(max_length=500, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='cookiepolicy',
            name='title_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='faqs',
            name='answer_ar',
            field=models.TextField(null=True, verbose_name='Answer'),
        ),
        migrations.AddField(
            model_name='faqs',
            name='answer_en',
            field=models.TextField(null=True, verbose_name='Answer'),
        ),
        migrations.AddField(
            model_name='faqs',
            name='quote_ar',
            field=models.CharField(max_length=1000, null=True, verbose_name='Quote'),
        ),
        migrations.AddField(
            model_name='faqs',
            name='quote_en',
            field=models.CharField(max_length=1000, null=True, verbose_name='Quote'),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='why_us_ar',
            field=models.TextField(null=True, verbose_name='Why do you choose us?'),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='why_us_en',
            field=models.TextField(null=True, verbose_name='Why do you choose us?'),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='description_ar',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='title_ar',
            field=models.CharField(max_length=500, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='title_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='termsofservice',
            name='description_ar',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='termsofservice',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='termsofservice',
            name='title_ar',
            field=models.CharField(max_length=500, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='termsofservice',
            name='title_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='works',
            name='description_ar',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='works',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='works',
            name='title_ar',
            field=models.CharField(max_length=500, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='works',
            name='title_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Title'),
        ),
    ]
